{"name": "test_sum", "status": "failed", "statusDetails": {"message": "AssertionError: 4 != 3 : 3 expection=3", "trace": "self = <unit.test_demo.TestDemo testMethod=test_sum>\n\n    def test_sum(self):\n        x = 1 + 2\n        print(x)\n>       self.assertEqual(4, x, f\"{x} expection=3\")\nE       AssertionError: 4 != 3 : 3 expection=3\n\nunit\\test_demo.py:22: AssertionError"}, "attachments": [{"name": "stdout", "source": "a5278bc6-234f-4f9f-9ebe-b614c63af697-attachment.txt", "type": "text/plain"}], "start": 1582965707973, "stop": 1582965707974, "uuid": "a154c71b-5648-4560-8800-325e6e2e9147", "historyId": "5390adf865abe5b81318f923b154e1f5", "testCaseId": "29216c7dc00751117849a4f95ff5904f", "fullName": "unit.test_demo.TestDemo#test_sum", "labels": [{"name": "parentSuite", "value": "unit"}, {"name": "suite", "value": "test_demo"}, {"name": "subSuite", "value": "TestDemo"}, {"name": "host", "value": "LAPTOP-GLFLRPL6"}, {"name": "thread", "value": "20968-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "unit.test_demo"}]}